services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lemontrip
      POSTGRES_PASSWORD: lemontrip
      POSTGRES_DB: lemontrip
    ports:
      - "5432:5432"
    volumes:
      - lemontrip-postgres:/var/lib/postgresql/data

volumes:
  lemontrip-postgres:
