CREATE TABLE IF NOT EXISTS content_items (
  id text PRIMARY KEY,
  content_type text NOT NULL CHECK (content_type IN ('package', 'blog', 'visa')),
  data jsonb NOT NULL,
  active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS content_items_type_active_idx ON content_items(content_type, active);

INSERT INTO content_items (id, content_type, data) VALUES
('pkg-1', 'package', '{"id":"pkg-1","title":"Dubai Luxury Escape","image":"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=85","duration":"5 Nights / 6 Days","rating":"★ 4.9","badge":"BEST SELLER","price":"₹24,999","description":"Experience the glitz and glamour of Dubai with luxury stays, desert safaris, and iconic skyline views.","highlights":["Desert Safari","Burj Khalifa Visit","Luxury Hotel Stay"],"destination":"Dubai","categories":["Luxury","Adventure","International"]}'),
('pkg-2', 'package', '{"id":"pkg-2","title":"Bali Signature Journey","image":"https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=85","duration":"6 Nights / 7 Days","rating":"★ 4.8","badge":"POPULAR","price":"₹32,999","description":"Explore the tropical paradise of Bali with its stunning beaches, ancient temples, and vibrant culture.","highlights":["Temple Tours","Beach Resorts","Cultural Experiences"],"destination":"Bali","categories":["International"]}'),
('pkg-3', 'package', '{"id":"pkg-3","title":"Kashmir Scenic Retreat","image":"https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&q=85","duration":"5 Nights / 6 Days","rating":"★ 4.9","badge":"LUXURY","price":"₹15,999","description":"Discover the breathtaking beauty of Kashmir with houseboats, snow-capped mountains, and lush gardens.","highlights":["Houseboat Stay","Shikara Ride","Mountain Views"],"destination":"Kashmir","categories":["Luxury","Domestic"]}'),
('blog-1', 'blog', '{"id":"blog-1","category":"Destinations","date":"Apr 22, 2026","title":"Best Hill Stations to Visit in India This Summer","excerpt":"Escape the heat with these stunning hill stations across India. From Shimla to Munnar, plan your perfect getaway.","image":"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=85","author":"LemonTrip editorial","readingTime":"6 min read","content":["When the summer heat settles in, the best escape is often higher ground. India is full of mountain towns where cool mornings, long walks, and unhurried meals become part of the itinerary.","Kashmir is a natural place to begin. Stay close to the water, make time for a shikara ride, and leave room for the landscape to set the pace.","For a smoother summer journey, book transport and stays early, pack one warm layer for evenings, and keep a flexible day for weather."],"relatedDestinationIds":["kashmir"],"relatedPackageIds":["pkg-3"]}'),
('blog-2', 'blog', '{"id":"blog-2","category":"Travel Tips","date":"Mar 08, 2026","title":"Business Travel: Packing Light for Short Trips","excerpt":"Master the art of minimalist packing for business trips. Look sharp with just a carry-on bag.","image":"https://images.unsplash.com/photo-1553877522-43269d4ea984?w=900&q=85","author":"LemonTrip editorial","readingTime":"4 min read","content":["A short business trip rewards a small, deliberate bag. Start with one versatile outfit for the meeting, one comfortable travel look, and shoes that can handle a full day.","Use a simple three-part system: a slim packing cube for clothes, a protected sleeve for documents, and one small pouch for cables.","Dubai makes an excellent test for this approach. Choose breathable layers and keep a light overshirt within reach."],"relatedDestinationIds":["dubai"],"relatedPackageIds":["pkg-1"]}'),
('blog-3', 'blog', '{"id":"blog-3","category":"Budget Travel","date":"Feb 14, 2026","title":"How to Travel India on ₹500 a Day","excerpt":"Smart budgeting tips for exploring India without breaking the bank. From street food to budget stays.","image":"https://images.unsplash.com/photo-1564507592333-c60657eea523?w=900&q=85","author":"LemonTrip editorial","readingTime":"5 min read","content":["Budget travel works best when the plan is clear but not rigid. Spend first on getting where you want to go, then let local food, public transport, and free walking routes shape the rest of the day.","A useful daily rhythm is one paid anchor activity, one simple meal, and plenty of time outdoors.","For a longer escape, compare the total journey rather than a single ticket price."],"relatedDestinationIds":["kashmir"],"relatedPackageIds":["pkg-3"]}'),
('visa-uae', 'visa', '{"code":"UAE","name":"United Arab Emirates","image":"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&q=85","visaTypes":["Tourist Visa"],"processing":"3–5 days","fee":"₹4,500"}'),
('visa-uk', 'visa', '{"code":"UK","name":"United Kingdom","image":"https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&q=85","visaTypes":["Business Visa","Student Visa"],"processing":"10–15 days (Business) · 15–30 days (Student)"}'),
('visa-usa', 'visa', '{"code":"USA","name":"United States","image":"https://images.unsplash.com/photo-1496588152823-86ff7695e68f?w=900&q=85","visaTypes":["Business Visa"],"processing":"10–15 days"}'),
('visa-canada', 'visa', '{"code":"Canada","name":"Canada","image":"https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=900&q=85","visaTypes":["Student Visa"],"processing":"15–30 days"}'),
('visa-australia', 'visa', '{"code":"Australia","name":"Australia","image":"https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=900&q=85","visaTypes":["Student Visa"],"processing":"15–30 days"}'),
('visa-schengen', 'visa', '{"code":"Schengen","name":"Schengen Area","image":"https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=900&q=85","visaTypes":["Business Visa"],"processing":"10–15 days","fee":"₹7,200"}'),
('visa-singapore', 'visa', '{"code":"Singapore","name":"Singapore","image":"https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=900&q=85","visaTypes":["Tourist Visa"],"processing":"3–5 days"}'),
('visa-thailand', 'visa', '{"code":"Thailand","name":"Thailand","image":"https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=900&q=85","visaTypes":["Tourist Visa"],"processing":"3–5 days"}')
ON CONFLICT (id) DO NOTHING;
